import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { AlertCircle, CheckCircle2, FileArchive, FolderUp, LoaderCircle } from 'lucide-react'
import { useRef, useState } from 'react'
import { Button } from '../components/ui/Button'
import { Card } from '../components/ui/Card'
import { fetchRepositories, type Repository, uploadRepository } from '../lib/api'

const MAX_UPLOAD_BYTES = 100 * 1024 * 1024
const formatBytes = (value: number) => `${(value / 1024 / 1024).toFixed(value > 1024 * 1024 ? 1 : 2)} MB`

export function UploadPage() {
  const [dragging, setDragging] = useState(false); const [progress, setProgress] = useState(0); const [error, setError] = useState<string | null>(null); const [preview, setPreview] = useState<Repository | null>(null)
  const inputRef = useRef<HTMLInputElement>(null); const client = useQueryClient()
  const history = useQuery({ queryKey: ['repositories'], queryFn: fetchRepositories })
  const upload = useMutation({ mutationFn: (file: File) => uploadRepository(file, setProgress), onSuccess: (repository) => { setPreview(repository); setError(null); client.invalidateQueries({ queryKey: ['repositories'] }) }, onError: (reason: unknown) => { const message = typeof reason === 'object' && reason && 'response' in reason ? (reason as { response?: { data?: { error?: { message?: string } } } }).response?.data?.error?.message : undefined; setError(message ?? 'Upload failed. Confirm the API is running and try again.') } })
  const selectFile = (file?: File) => { if (!file) return; setError(null); setPreview(null); setProgress(0); if (!file.name.toLowerCase().endsWith('.zip')) { setError('Only .zip repository archives are supported.'); return }; if (file.size > MAX_UPLOAD_BYTES) { setError('Archive exceeds the 100 MB upload limit.'); return }; upload.mutate(file) }
  return <><h1 className="text-2xl font-semibold">Repository upload</h1><p className="mt-2 text-sm text-slate-400">Upload a ZIP archive to prepare a repository for analysis.</p><div className="mt-7 grid gap-5 lg:grid-cols-[1.3fr_1fr]"><Card className="p-6"><input ref={inputRef} className="hidden" type="file" accept=".zip,application/zip" onChange={(event) => selectFile(event.target.files?.[0])} /><div onDragOver={(event) => { event.preventDefault(); setDragging(true) }} onDragLeave={() => setDragging(false)} onDrop={(event) => { event.preventDefault(); setDragging(false); selectFile(event.dataTransfer.files[0]) }} onClick={() => inputRef.current?.click()} className={`grid min-h-64 cursor-pointer place-items-center rounded-lg border border-dashed p-8 text-center transition ${dragging ? 'border-blue-400 bg-blue-500/10' : 'border-[#30363d] bg-[#0d1117] hover:border-slate-500'}`}><div>{upload.isPending ? <LoaderCircle className="mx-auto size-8 animate-spin text-blue-400" /> : <FolderUp className="mx-auto size-8 text-blue-400" />}<h2 className="mt-4 font-medium">{upload.isPending ? 'Uploading repository…' : 'Drop a ZIP archive here'}</h2><p className="mt-2 text-sm text-slate-400">or click to browse · ZIP only · max 100 MB</p>{upload.isPending && <div className="mx-auto mt-5 w-56"><div className="h-2 overflow-hidden rounded bg-[#30363d]"><div className="h-full bg-blue-500 transition-all" style={{ width: `${progress}%` }} /></div><p className="mt-2 text-xs text-slate-400">{progress}% uploaded</p></div>}</div></div>{error && <div className="mt-4 flex gap-2 rounded-md border border-red-900/70 bg-red-950/30 p-3 text-sm text-red-200"><AlertCircle className="size-4 shrink-0" />{error}</div>}{preview && <MetadataPreview repository={preview} />}</Card><Card className="p-6"><h2 className="font-medium">Upload history</h2><p className="mt-1 text-sm text-slate-400">Repositories stored by this workspace.</p><div className="mt-5 space-y-3">{history.isLoading && <p className="text-sm text-slate-500">Loading history…</p>}{history.isError && <p className="text-sm text-red-300">Could not load upload history.</p>}{history.data?.length === 0 && <p className="text-sm text-slate-500">No uploads yet.</p>}{history.data?.map((repository) => <div key={repository.project_id} className="rounded-md border border-[#30363d] bg-[#0d1117] p-3"><div className="flex items-center gap-2"><FileArchive className="size-4 text-violet-400" /><span className="truncate text-sm font-medium">{repository.name}</span></div><p className="mt-1 text-xs text-slate-500">{repository.file_count} files · {repository.supported_languages.join(', ') || 'No language detected'}</p></div>)}</div></Card></div></>
}

function MetadataPreview({ repository }: { repository: Repository }) { return <div className="mt-5 rounded-lg border border-emerald-800/70 bg-emerald-950/20 p-4"><div className="flex items-center gap-2 text-emerald-300"><CheckCircle2 className="size-5" /><span className="font-medium">Repository ready</span></div><div className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><p><span className="text-slate-500">Project ID</span><br />{repository.project_id}</p><p><span className="text-slate-500">Archive size</span><br />{formatBytes(repository.archive_size_bytes)}</p><p><span className="text-slate-500">Files</span><br />{repository.file_count}</p><p><span className="text-slate-500">Languages</span><br />{repository.supported_languages.join(', ') || 'None detected'}</p></div></div> }
